# Cloudflare Pages Configuration
name = "mirestaurante-template"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"
dir = "dist"

# Environment variables (if needed for build)
[env.production]
NODE_ENV = "production"

# Redirects and rewrites
[[redirects]]
from = "/sitemap.xml"
to = "https://ptzcetvcccnojdbzzlyt.supabase.co/functions/v1/generate-sitemap"
status = 200
